---
# Organization to pull metrics from
organization: 'mooniak dashboard'

# Start date to pull metrics from
since: '2015-01-01'

# GitHub Pages path to the repository
# Used for handling relative paths for assets
basePath: '/dashboard'
